### PR TITLE
Refine `models` directory

### LINKED ISSUE #54: Refine `models` directory
The `models` directory needs to contain two parts. The first part is some standard model configuration files, such as MobileNet, ResNet, etc., that can be used as benchmark test data. The second part contains some well-trained model parameter files, such as the `mobilenet ssd pascal model`, which can be directly converted to inference model files for deployment to mobile.

### PR DESCRIPTION
**Pull request by hedaoyuan**
Fix #54

### CODE REVIEW

**Comment by Xreki** [comment]
I agree to reorganize  the directory, but I am not sure about the sub-directories' name.

**Comment by Xreki** [comment]
In fact, I think the sub-directories' name under `deployment` is not intuitive. Since #54 is merged, we may keep it and change it in next PR. 

About the sub-directory under `models`, how about change `configuration` to `standard_network_configs`?

**Comment by hedaoyuan** [comment]
> About the sub-directory under models, how about change configuration to standard_network_configs?

OK. I will change the directory name to `standard_network`, and also we can add a README.md to explain the configuration is follow which article.

**Comment by Xreki** [comment]
> we can add a README.md to explain the configuration is follow which article.

Yes, indeed we need to add this. Maybe @NHZlX add this in next PR?

**Review by Xreki — APPROVED** [review]

**Pull request merged**
